project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "radar-cookbook"
  site-url: "https://rbagdazian.github.io/radar-cookbook"
  description: "A collection of useful tools applicable to radar design work"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/rbagdazian/radar-cookbook"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/rbagdazian/radar-cookbook"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
