# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/radar-cookbook',
                'doc_host': 'https://rbagdazian.github.io',
                'git_url': 'https://github.com/rbagdazian/radar-cookbook',
                'lib_path': 'radar_cookbook'},
  'syms': {'radar_cookbook.core': {'radar_cookbook.core.foo': ('core.html#foo', 'radar_cookbook/core.py')}}}