# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/radar-cookbook',
                'doc_host': 'https://rbagdazian.github.io',
                'git_url': 'https://github.com/rbagdazian/radar-cookbook',
                'lib_path': 'radar_cookbook'},
  'syms': { 'radar_cookbook.core': {'radar_cookbook.core.foo': ('radar_cookbook.html#foo', 'radar_cookbook/core.py')},
            'radar_cookbook.radar-cookbook': { 'radar_cookbook.radar-cookbook.foo': ( 'radar_cookbook.html#foo',
                                                                                      'radar_cookbook/radar-cookbook.py')},
            'radar_cookbook.radar_cookbook': { 'radar_cookbook.radar_cookbook.foo': ( 'radar_cookbook.html#foo',
                                                                                      'radar_cookbook/radar_cookbook.py')},
            'radar_cookbook.radarcookbook': { 'radar_cookbook.radarcookbook.foo': ( 'radarcookbook.html#foo',
                                                                                    'radar_cookbook/radarcookbook.py')}}}